//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DTEntities : DbContext
    {
        public DTEntities()
            : base("name=DTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_tblActivity> C_tblActivity { get; set; }
        public virtual DbSet<C_tblBooking> C_tblBooking { get; set; }
        public virtual DbSet<C_tblCourses> C_tblCourses { get; set; }
        public virtual DbSet<C_tblUserReg> C_tblUserReg { get; set; }
    }
}
