//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblCourses
    {
        public int CourseID { get; set; }
        public string CourseList { get; set; }
        public string CourseDuration { get; set; }
        public Nullable<System.DateTime> starttimestamp { get; set; }
        public Nullable<System.DateTime> endtimestamp { get; set; }
        public decimal Amount { get; set; }
        public int RoleID { get; set; }
    
        public virtual C_tblUserReg C_tblUserReg { get; set; }
    }
}
