//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblUserReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblUserReg()
        {
            this.C_tblActivity = new HashSet<C_tblActivity>();
            this.C_tblCourses = new HashSet<C_tblCourses>();
        }
    
        public int roleID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string emailAddress { get; set; }
        public string phoneNumber { get; set; }
        public string Address { get; set; }
        public string Userrole { get; set; }
        public string password { get; set; }
        public string APhonenumber { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblActivity> C_tblActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblCourses> C_tblCourses { get; set; }
    }
}
