//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblBooking
    {
        public int BookID { get; set; }
        public string BookingReason { get; set; }
        public System.DateTime Starttimestamp { get; set; }
        public Nullable<System.DateTime> Endtimestamp { get; set; }
        public int RoleID { get; set; }
        public int ActivityID { get; set; }
    
        public virtual C_tblBooking C_tblBooking1 { get; set; }
        public virtual C_tblBooking C_tblBooking2 { get; set; }
    }
}
