//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblActivity
    {
        public int ActivityID { get; set; }
        public string ActivityNames { get; set; }
        public int RoleID { get; set; }
        public int CourseID { get; set; }
    
        public virtual C_tblUserReg C_tblUserReg { get; set; }
    }
}
